### PR TITLE
Week02

### PR DESCRIPTION
**Pull request by Ahmed-Joyee**
Linked List problem solutions for week 02

### CODE REVIEW

**Comment by Sadman007** [comment]
Bad PR. Rejected.

**Comment by Ahmed-Joyee** [comment]
Bhaiya,
I would like to know exactly where I went wrong creating the PR. I followed
the exact same steps as week 01 and that was accepted. I would be grateful
for a clarification so that I don't repeat the same mistakes next week. I
believe my request adhered to the following:
1. a separate branch from main and week 1
2. TC/MC included for each solution
3. no debug statements in final solutions
4. one solution for each problem
5. no other files except solutions
6. the function names are used as given in the leetcode template

Thank you

**Comment by Sadman007** [comment]
You uploaded all the solutions in the root dir of the repository. You need to create a separate folder in the root dir named `week02` and put all your solutions there.

If I approved your PR and let you merge that, imagine what would happen. Where would you put your solutions for week03? On the root dir again? How would you differentiate between different weeks?

**Comment by Sadman007** [comment]
Reference:

image

**Comment by Ahmed-Joyee** [comment]
Thank you for the clarification. Would you let me reopen the PR if I create
a directory now? I will not repeat the same mistake again.

**Pull request merged**
